name='洛萦'
age=20
print(name,type(name))
print(age,type(age))
print('我叫'+name+'今年'+str(age))
a=33
b=6.4
c='fy'
print(a,type(a))
print(b,type(b))
print(c,type(c))
print(str(a),str(b),str(c))
print(str(a),str(b),str(c),type(str(a)),type(str(b)),type(str(c)))
q='3364'
w=94.64
e=True
print(int(q),int(w),int(e))
r='123.数学建模'
g='456'
j=True
m=56
print(float(r),float(g),float(j),float(m))